title: <p align="center"> Balaji Sreedhar </p>
logo: /assets/img/Balaji.jpg

description:
<br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
